import type { Database } from '@/integrations/supabase/types';

type Entegrator = Database['public']['Tables']['entegrator']['Row'];
type Firma = Database['public']['Tables']['firma']['Row'];

export type MockEntegrator = Entegrator & {
  detayli_puanlar?: {
    kalite: number;
    musteri_iliskisi: number;
    surec: number;
  };
  yorum_listesi?: Array<{kalite_puan: number, musteri_iliskisi_puan: number, surec_yonetimi_puan: number, yorum: string, created_at: string, author?: string}>;
};

const rawEntegratorler: any[] = [
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556601',
    entegrator_adi: 'RoboTech Otomasyon',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Goruntu Isleme, PLC Programlama, CNC Besleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@robotech.com.tr',
    kac_kisi: 15,
    konum: 'Bursa, NOSAB',
    yorum_listesi: [
          {
                "kalite_puan": 4.6,
                "musteri_iliskisi_puan": 4,
                "surec_yonetimi_puan": 4.2,
                "yorum": "Robotik kaynak hücresi devreye alınırken ilk hafta ark sapmıyor, kaynak dikis kalitesi spesifikasyonun üstünde (±0.3µm). Parametreleri telefonla anlatıldı, daha iyi belgeleme beklerdik.",
                "created_at": "2026-02-02T20:32:35.395Z",
                "author": "Serhat K. - Uretim Muduru"
          },
          {
                "kalite_puan": 4.4,
                "musteri_iliskisi_puan": 5,
                "surec_yonetimi_puan": 3.8,
                "yorum": "SCADA sisteminde üretim verisi 4 saniye gecikmeli akmıştı; Siemens S7-1500 tarafında byte offset hatası tespit edildi. Üretici bunu düzeltmeden teslim etti ama remote destek 2 saatte çözdü.",
                "created_at": "2025-07-25T09:32:18.969Z",
                "author": "Gokhan B. - Proje Yoneticisi"
          }
    ],
    referans: 'Hat Sonu Paletleme Entegrasyonu, Scada Sistemleri.',
    sektor: 'Plastik',
    tecrube: '19 yıl',
    uzmanlik_alani: 'Punta Kaynak, AGV Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@robotech.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556602',
    entegrator_adi: 'MechSys Endustriyel Cozumler',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'Scada Sistemleri, PLC Programlama, Hat Sonu Paletleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@mechsys.com.tr',
    kac_kisi: 11,
    konum: 'Istanbul, DES Sanayi',
    yorum_listesi: [
          {
                "kalite_puan": 5,
                "musteri_iliskisi_puan": 4.2,
                "surec_yonetimi_puan": 4.8,
                "yorum": "Hat sonu paletleme hızı saatte 1 200 kutuda kaldı, teklifteki 1 400 hedefine ulaşılamadı. Mekanik yeniden çalişılarak 6 haftada hedef yakalandı, geçikme can sıktı.",
                "created_at": "2025-12-12T11:18:56.803Z",
                "author": "Ahmet T. - Lojistik Sefi"
          },
          {
                "kalite_puan": 4.8,
                "musteri_iliskisi_puan": 4.6,
                "surec_yonetimi_puan": 4.2,
                "yorum": "AGV filosu 18 aracın tümü zamanlamaya uydu, depo trafik algoritması yerinde yazıldı. Devreye alma sürecinde hiç durmaksızın üretim devam etti — çok başarılı bir planlama.",
                "created_at": "2025-07-17T12:25:52.609Z",
                "author": "Caner D. - Ar-Ge Sorumlusu"
          }
    ],
    referans: 'AGV Sistemleri Entegrasyonu, Robotik Kaynak.',
    sektor: 'Gida',
    tecrube: '9 yıl',
    uzmanlik_alani: 'Robotik Kaynak, AGV Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@mechsys.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556603',
    entegrator_adi: 'AutoLine Robotik',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Scada Sistemleri, PLC Programlama, Punta Kaynak',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@autoline.com.tr',
    kac_kisi: 14,
    konum: 'Izmir, ITOB',
    yorum_listesi: [
          {
                "kalite_puan": 3.8,
                "musteri_iliskisi_puan": 4.8,
                "surec_yonetimi_puan": 3.4,
                "yorum": "Görüntü işleme sistemine 0.05µm ince hata tespiti görevi verildi. Testlerde %99.2 doğru sonuç alındı, ancak kamera tutucusu tıtreme yapıyordu; çelik levha eklenerek çözüldü.",
                "created_at": "2026-02-07T11:47:10.308Z",
                "author": "Elif M. - Otomasyon Lideri"
          },
          {
                "kalite_puan": 3.4,
                "musteri_iliskisi_puan": 4.2,
                "surec_yonetimi_puan": 3,
                "yorum": "PLC programı hattı yeniden yazılırken 3 farklı Omron ünitesi tek merkezi haberleşmeye bağlanmalıydı. Protokol dönüşümü başlangıçta sorun çıkardı, son haliyle çok temiz çalışıyor.",
                "created_at": "2025-06-16T05:21:26.759Z",
                "author": "Mehmet Y. - Elektrik Bakim Sefi"
          }
    ],
    referans: 'Hat Sonu Paletleme Entegrasyonu, Robotik Kaynak.',
    sektor: 'Savunma Sanayi',
    tecrube: '23 yıl',
    uzmanlik_alani: 'Goruntu Isleme, PLC Programlama',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@autoline.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556604',
    entegrator_adi: 'SmartFab Sistemleri',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'AGV Sistemleri, Robotik Kaynak, CNC Besleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@smartfab.com.tr',
    kac_kisi: 142,
    konum: 'Bursa, NOSAB',
    yorum_listesi: [
          {
                "kalite_puan": 4.2,
                "musteri_iliskisi_puan": 3.6,
                "surec_yonetimi_puan": 4.6,
                "yorum": "Kestirimci bakım modülü 3 ayda toplam 9 planlanmamış duruluyor önledi. Titreşim sensörleri doğru yerleştirilmiş, analitik panel operatif açıdan anlaşılır.",
                "created_at": "2026-01-30T11:32:21.920Z",
                "author": "Kemal S. - Satinalma Muduru"
          },
          {
                "kalite_puan": 4.8,
                "musteri_iliskisi_puan": 3.4,
                "surec_yonetimi_puan": 4.4,
                "yorum": "Punta kaynak robotunda ilk 200 parcada merkezleme sapması oluştu. Firma hızlı araya girdi ve fixture toleransını sıfırlamakla çözdü; bu hızdaki yanıt takdire şayan.",
                "created_at": "2025-07-30T10:59:02.786Z",
                "author": "Ayse K. - Isletme Muduru"
          }
    ],
    referans: 'Scada Sistemleri Entegrasyonu, PLC Programlama.',
    sektor: 'Otomotiv Ana Sanayi',
    tecrube: '14 yıl',
    uzmanlik_alani: 'Punta Kaynak, Kestirimci Bakim',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@smartfab.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556605',
    entegrator_adi: 'Ileri Hareket Otomasyon',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'Scada Sistemleri, PLC Programlama, Robotik Kaynak',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@ileri.com.tr',
    kac_kisi: 70,
    konum: 'Istanbul, DES Sanayi',
    yorum_listesi: [
          {
                "kalite_puan": 3,
                "musteri_iliskisi_puan": 3.8,
                "surec_yonetimi_puan": 2.8,
                "yorum": "Konveyör hız eşitlemesi otomotiv hattı ciklü zamanlarıyla eşleştirildi. Mekanik montaj hatasız, ama elektrik şemalama belgeleri geçici CAD olarak kaldı — as-built bekliyoruz.",
                "created_at": "2025-12-22T10:04:27.228Z",
                "author": "Zeynep P. - Kalite Kontrol Sefi"
          },
          {
                "kalite_puan": 3.6,
                "musteri_iliskisi_puan": 4.2,
                "surec_yonetimi_puan": 3.2,
                "yorum": "Makine besleme ünitesi 14” liğer döküm parçaları için optimize edildi. İlk 300 çevrimde düşenme çıkışı sıfıra indi; kapasite garantisi eksiksiz yerine getirildi.",
                "created_at": "2025-06-27T09:54:13.980Z",
                "author": "Hakan E. - Uretim Muhendisi"
          }
    ],
    referans: 'Robotik Kaynak Entegrasyonu, Kestirimci Bakim.',
    sektor: 'Otomotiv Ana Sanayi',
    tecrube: '22 yıl',
    uzmanlik_alani: 'CNC Besleme, Kestirimci Bakim',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@ileri.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556606',
    entegrator_adi: 'CoreRobotics',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Robotik Kaynak, Scada Sistemleri, Makine Besleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@corerobotics.com.tr',
    kac_kisi: 64,
    konum: 'Sakarya, 1. OSB',
    yorum_listesi: [
          {
                "kalite_puan": 4.8,
                "musteri_iliskisi_puan": 4.8,
                "surec_yonetimi_puan": 4.6,
                "yorum": "Savunma sanayi parçası lazer kesim entegrasyonu NATO sertifikası gerektirdi. Tüm dokümantasyon tam ve zamanında teslim edildi, müfettiş denetiminde sıfır bulgu.",
                "created_at": "2026-01-10T23:38:04.695Z",
                "author": "Fatih C. - Uretim Sorumlusu"
          },
          {
                "kalite_puan": 5,
                "musteri_iliskisi_puan": 4.6,
                "surec_yonetimi_puan": 5,
                "yorum": "Gıda paketleme hattında ISO 22000 hijyen gereksinimleri nedeniyle robot bileşenleri paslanmaz çelik kaplamaya dönüştürüldü. Üretici bu konuda deneyimli ve önerisi isabetli çıktı.",
                "created_at": "2025-06-08T02:21:50.618Z",
                "author": "Burak L. - Fabrika Direktoru"
          }
    ],
    referans: 'Hat Sonu Paletleme Entegrasyonu, Scada Sistemleri.',
    sektor: 'Gida',
    tecrube: '24 yıl',
    uzmanlik_alani: 'Hat Sonu Paletleme, PLC Programlama',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@corerobotics.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556607',
    entegrator_adi: 'Apex Otomasyon Teknolojileri',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'CNC Besleme, Robotik Kaynak, Kestirimci Bakim',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@apex.com.tr',
    kac_kisi: 64,
    konum: 'Sakarya, 1. OSB',
    yorum_listesi: [
          {
                "kalite_puan": 3.4,
                "musteri_iliskisi_puan": 3,
                "surec_yonetimi_puan": 3.8,
                "yorum": "Tekstil fabrikasında boyahane lojistiği için AGV güzergaıhı yazan yazılım dinamik engel algılaması yüzünden 2 kez yeniden çaltıldı. Sonunda stabil ancak daha erken test edilebilirdi.",
                "created_at": "2026-02-24T06:16:58.210Z",
                "author": "Tugrul H. - Bakim Muhendisi"
          },
          {
                "kalite_puan": 3.8,
                "musteri_iliskisi_puan": 3.4,
                "surec_yonetimi_puan": 3.6,
                "yorum": "CNC tezgah besleme robotu 4 eksenli, 18 kg yük aldı. Yükleme döngüsü 8 saniye — teklifteki 9 saniyenin altında. Önerilen yakılaştirma çıkış konumu mükemmel çalıştı.",
                "created_at": "2025-08-24T18:59:10.410Z",
                "author": "Cemre T. - Teknik Mudur"
          }
    ],
    referans: 'Punta Kaynak Entegrasyonu, AGV Sistemleri.',
    sektor: 'Beyaz Esya',
    tecrube: '7 yıl',
    uzmanlik_alani: 'Robotik Kaynak, AGV Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@apex.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556608',
    entegrator_adi: 'VisionTech Makine',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Robotik Kaynak, Goruntu Isleme, Makine Besleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@visiontech.com.tr',
    kac_kisi: 31,
    konum: 'Istanbul, DES Sanayi',
    yorum_listesi: [
          {
                "kalite_puan": 4.4,
                "musteri_iliskisi_puan": 4.6,
                "surec_yonetimi_puan": 4.2,
                "yorum": "İlaç ambalaj hattında süreklilik önemliydi; firma gece shift’iyle devreye aldı. Hipersteril oda sertifikası aldıkça prosedEr adlandı düşürmüştü ama düzeltti.",
                "created_at": "2026-05-03T04:14:21.806Z",
                "author": "Okan V. - ISG Uzmani"
          },
          {
                "kalite_puan": 4.6,
                "musteri_iliskisi_puan": 4.4,
                "surec_yonetimi_puan": 4.4,
                "yorum": "Elektronik kart test otomasyon sistemi ıskalası fabrikasına kuruldu. Vision tarafı çalışıyor ancak raporlama modülü kaçınması gereken false-positive üretiyor, güncelleme bekliyor.",
                "created_at": "2025-07-29T01:06:05.454Z",
                "author": "Gulsah N. - Proje Uzmani"
          }
    ],
    referans: 'Goruntu Isleme Entegrasyonu, Robotik Kaynak.',
    sektor: 'Otomotiv Yan Sanayi',
    tecrube: '12 yıl',
    uzmanlik_alani: 'Robotik Kaynak, AGV Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@visiontech.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556609',
    entegrator_adi: 'Nova Robotik Sistemler',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'Goruntu Isleme, Scada Sistemleri, Hat Sonu Paletleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@nova.com.tr',
    kac_kisi: 67,
    konum: 'Kocaeli, GOSB',
    yorum_listesi: [
          {
                "kalite_puan": 4,
                "musteri_iliskisi_puan": 5,
                "surec_yonetimi_puan": 4,
                "yorum": "Plastik enjeksiyon tezgahının robot araçlığı sprue kesici entegrasyonu beklenmedik vakum başarısızlığına uğradi. Tasarimi revize ettiler, kalite daha iyi.",
                "created_at": "2026-03-06T18:08:34.435Z",
                "author": "Yasin F. - Gida Muhendisi"
          },
          {
                "kalite_puan": 4.2,
                "musteri_iliskisi_puan": 4.8,
                "surec_yonetimi_puan": 4.2,
                "yorum": "Metal bükme ve presleme hücresinde servo kaynaklı parça poz pozlaması çok hassas. 6 saat mühendisin saha desteği ile yapılandırma tamamlandı.",
                "created_at": "2025-08-14T07:03:37.101Z",
                "author": "Ece D. - Kalite Guvence"
          }
    ],
    referans: 'AGV Sistemleri Entegrasyonu, Robotik Kaynak.',
    sektor: 'Ilac',
    tecrube: '12 yıl',
    uzmanlik_alani: 'Hat Sonu Paletleme, AGV Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@nova.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556610',
    entegrator_adi: 'GigaMekatronik',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Punta Kaynak, Robotik Kaynak, Kestirimci Bakim',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@gigamekatronik.com.tr',
    kac_kisi: 92,
    konum: 'Istanbul, DES Sanayi',
    yorum_listesi: [
          {
                "kalite_puan": 3.2,
                "musteri_iliskisi_puan": 3.6,
                "surec_yonetimi_puan": 3,
                "yorum": "Depo otomasyon sisteminde RF barkod okuyucu şeridsği firmware hatası kaynaklı çökme yaşıyordu. Firmware güncellemesi sonrası kesintisiz çalıştı.",
                "created_at": "2026-02-04T04:00:15.534Z",
                "author": "Dogan R. - Preshane Sefi"
          },
          {
                "kalite_puan": 3.6,
                "musteri_iliskisi_puan": 3.2,
                "surec_yonetimi_puan": 3.4,
                "yorum": "Ambalaj hattı robot pnomatik sistemi yeni çift-katlı valf grubuyla yenilendi. Gücü düşükken yavaslayan kol sorunu çözüldü; verimlilik %18 arttı.",
                "created_at": "2025-07-25T18:50:13.157Z",
                "author": "Bulent M. - Yatirim Muduru"
          }
    ],
    referans: 'Punta Kaynak Entegrasyonu, AGV Sistemleri.',
    sektor: 'Otomotiv Ana Sanayi',
    tecrube: '24 yıl',
    uzmanlik_alani: 'Punta Kaynak, Scada Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@gigamekatronik.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556611',
    entegrator_adi: 'Nodus Robotik',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'AGV Sistemleri, Robotik Kaynak, Hat Sonu Paletleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@nodus.com.tr',
    kac_kisi: 121,
    konum: 'Manisa, MOSB',
    yorum_listesi: [
          {
                "kalite_puan": 5,
                "musteri_iliskisi_puan": 5,
                "surec_yonetimi_puan": 4.8,
                "yorum": "Otomotiv karoser kaynak hattı entegrasyonunda jig toleransı ±0.1 mm'ye düşürüldü. 3 yeni robot kola ek olarak mevcut 5 kol da yeniden kalibre edildi, hepsi tek oturumda.",
                "created_at": "2026-04-01T19:56:33.826Z",
                "author": "Cengiz K. - Guvenlik Muduru"
          },
          {
                "kalite_puan": 4.8,
                "musteri_iliskisi_puan": 4.8,
                "surec_yonetimi_puan": 5,
                "yorum": "Härterei fırın sıcaklık SCADA izleme sistemi kuruldu. Alarm eşiği yanlış ayarlanmıştı, ilk haftada gerçek alarm olmayan tetikleme oluştu ama hızlı düzeldi.",
                "created_at": "2025-08-03T03:57:42.845Z",
                "author": "Alper T. - CNC Sorumlusu"
          }
    ],
    referans: 'Kestirimci Bakim Entegrasyonu, Scada Sistemleri.',
    sektor: 'Otomotiv Yan Sanayi',
    tecrube: '7 yıl',
    uzmanlik_alani: 'Makine Besleme, Kestirimci Bakim',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@nodus.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556612',
    entegrator_adi: 'Optima Otomasyon',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Hat Sonu Paletleme, AGV Sistemleri, PLC Programlama',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@optima.com.tr',
    kac_kisi: 106,
    konum: 'Sakarya, 1. OSB',
    yorum_listesi: [
          {
                "kalite_puan": 4.4,
                "musteri_iliskisi_puan": 4,
                "surec_yonetimi_puan": 4.6,
                "yorum": "Gıda düzültme ve küpürdatma hattında vision sistemi renk bazlı kusur tespiti yapıyor. Performans beklenenden iyi; erken teslim bile gerçekleşti.",
                "created_at": "2026-01-10T05:58:02.206Z",
                "author": "Selim B. - Validasyon Uzmani"
          },
          {
                "kalite_puan": 4.6,
                "musteri_iliskisi_puan": 4.2,
                "surec_yonetimi_puan": 4.4,
                "yorum": "Proje boyunca gerçek zamanlı haftalık ilerleme raporu alındı. Bazı raporlar veri eksikti ama hafta içinde tamamlandı.",
                "created_at": "2025-06-22T11:34:16.333Z",
                "author": "Merve K. - Regulasyon Muduru"
          }
    ],
    referans: 'Hat Sonu Paletleme Entegrasyonu, Punta Kaynak.',
    sektor: 'Otomotiv Ana Sanayi',
    tecrube: '21 yıl',
    uzmanlik_alani: 'Scada Sistemleri, Hat Sonu Paletleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@optima.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556613',
    entegrator_adi: 'CyberMekatronik',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'Robotik Kaynak, Goruntu Isleme, PLC Programlama',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@cybermekatronik.com.tr',
    kac_kisi: 110,
    konum: 'Gaziantep OSB',
    yorum_listesi: [
          {
                "kalite_puan": 3.6,
                "musteri_iliskisi_puan": 4.6,
                "surec_yonetimi_puan": 3.8,
                "yorum": "Robot yeniden programlama sürecinde üretim 6 saat durdu, planıanan 4 saat yerine. Ek mesai bedeli tazmin edilmedi; sözleşme nettir.",
                "created_at": "2026-01-08T18:39:14.371Z",
                "author": "Turgut C. - Boyahane Sefi"
          },
          {
                "kalite_puan": 3.8,
                "musteri_iliskisi_puan": 4.4,
                "surec_yonetimi_puan": 3.4,
                "yorum": "Devreye alma sonrası ilk ayda 3 kez teknik ekip sahıya geldi. Her defasında sorunu uzaktan da çözebilirlerdi ama yerinde çözmeyi tercih ettiler.",
                "created_at": "2025-10-15T01:21:39.880Z",
                "author": "Nalan G. - Cevre Muhendisi"
          }
    ],
    referans: 'Robotik Kaynak Entegrasyonu, Punta Kaynak.',
    sektor: 'Beyaz Esya',
    tecrube: '3 yıl',
    uzmanlik_alani: 'PLC Programlama, CNC Besleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@cybermekatronik.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556614',
    entegrator_adi: 'ProLine Sistem',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'Kestirimci Bakim, Robotik Kaynak, Goruntu Isleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@proline.com.tr',
    kac_kisi: 108,
    konum: 'Sakarya, 1. OSB',
    yorum_listesi: [
          {
                "kalite_puan": 4.2,
                "musteri_iliskisi_puan": 3.8,
                "surec_yonetimi_puan": 4,
                "yorum": "Hat durma süresi ilk çeyrekte %2.1'den %0.4'e indi. En büyük katkı konveyör senkronizasyon iyileştirmesinden geldi.",
                "created_at": "2026-04-18T01:26:58.260Z",
                "author": "Orhan E. - Ambalaj Sefi"
          },
          {
                "kalite_puan": 4,
                "musteri_iliskisi_puan": 3.4,
                "surec_yonetimi_puan": 4.2,
                "yorum": "Üretim sırasında hattan geçen ilk 1000 parça sıfır hurda ile tamamlandı. Bazı hizalama ayarı gerekti ama sonunda mükemmel.",
                "created_at": "2025-11-09T22:43:30.216Z",
                "author": "Didem A. - Finans Sorumlusu"
          }
    ],
    referans: 'Scada Sistemleri Entegrasyonu, PLC Programlama.',
    sektor: 'Beyaz Esya',
    tecrube: '5 yıl',
    uzmanlik_alani: 'Makine Besleme, CNC Besleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@proline.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556615',
    entegrator_adi: 'Kinetik Endustriyel',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Kestirimci Bakim, AGV Sistemleri, Hat Sonu Paletleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@kinetik.com.tr',
    kac_kisi: 131,
    konum: 'Ankara, OSTIM',
    yorum_listesi: [
          {
                "kalite_puan": 4.8,
                "musteri_iliskisi_puan": 4.6,
                "surec_yonetimi_puan": 4.8,
                "yorum": "Sistem devreye alırken eski PLC ile yeni SCADA arasındaki Modbus haberleşmesi çaklıyordu. Çözüm bir hafta sürdü ama çok kalıcı.",
                "created_at": "2026-01-03T13:06:15.888Z",
                "author": "Sinan Y. - Montaj Muduru"
          },
          {
                "kalite_puan": 5,
                "musteri_iliskisi_puan": 4.8,
                "surec_yonetimi_puan": 4.6,
                "yorum": "Robot yolunu yeniden öğrenmeden önce simlasön çallıştırıldı, sahıda hiç çarpışma olmadı.",
                "created_at": "2025-06-16T11:02:43.723Z",
                "author": "Riza P. - Bas Muhendis"
          }
    ],
    referans: 'AGV Sistemleri Entegrasyonu, Goruntu Isleme.',
    sektor: 'Savunma Sanayi',
    tecrube: '11 yıl',
    uzmanlik_alani: 'Robotik Kaynak, PLC Programlama',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@kinetik.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556616',
    entegrator_adi: 'Nexus Makine',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Goruntu Isleme, PLC Programlama, Makine Besleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@nexus.com.tr',
    kac_kisi: 157,
    konum: 'Manisa, MOSB',
    yorum_listesi: [
          {
                "kalite_puan": 3.8,
                "musteri_iliskisi_puan": 4,
                "surec_yonetimi_puan": 3.8,
                "yorum": "Konveyör bantları gıda standartlarına uygun malzemeyle değiştirildi. Bant ek kalitesi beklentinin üstünde.",
                "created_at": "2026-05-03T10:42:09.775Z",
                "author": "Kaan M. - Kalite Teknisyeni"
          },
          {
                "kalite_puan": 4,
                "musteri_iliskisi_puan": 3.6,
                "surec_yonetimi_puan": 3.4,
                "yorum": "Güvenlik çiti lazer perdesiyle entegre edildi. İlk testlerde tetikleme gecikmesi standartın altındaydı; yeniden ayarlandı.",
                "created_at": "2025-07-17T17:43:04.989Z",
                "author": "Leman T. - Proses Kontrol"
          }
    ],
    referans: 'Kestirimci Bakim Entegrasyonu, Robotik Kaynak.',
    sektor: 'Metal Isleme',
    tecrube: '13 yıl',
    uzmanlik_alani: 'Makine Besleme, AGV Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@nexus.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556617',
    entegrator_adi: 'Aura Robotik',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'PLC Programlama, Makine Besleme, Goruntu Isleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@aura.com.tr',
    kac_kisi: 69,
    konum: 'Kocaeli, GOSB',
    yorum_listesi: [
          {
                "kalite_puan": 4.6,
                "musteri_iliskisi_puan": 4.8,
                "surec_yonetimi_puan": 4.4,
                "yorum": "Servo motor parametreleri fabıça sahaya gelip yerinde optimize etti. Ekstra gidip gelme hem zaman hem bizçin çaba harcattı ama sonunda sert çalıştı.",
                "created_at": "2025-11-15T08:14:20.974Z",
                "author": "Emre Z. - Atolye Sefi"
          },
          {
                "kalite_puan": 4.8,
                "musteri_iliskisi_puan": 4.6,
                "surec_yonetimi_puan": 4.8,
                "yorum": "Fabrikasımızdaki pres beslemede vakum kavrama basıncı tutarsız çıkıyordu; valf temizlenerek çözüldü, takip çok hızlıydı.",
                "created_at": "2025-05-25T02:12:42.334Z",
                "author": "Koray B. - Fabrika Muduru"
          }
    ],
    referans: 'Makine Besleme Entegrasyonu, Goruntu Isleme.',
    sektor: 'Otomotiv Ana Sanayi',
    tecrube: '4 yıl',
    uzmanlik_alani: 'Makine Besleme, Robotik Kaynak',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@aura.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556618',
    entegrator_adi: 'Sentetik Otomasyon',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Scada Sistemleri, AGV Sistemleri, CNC Besleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@sentetik.com.tr',
    kac_kisi: 117,
    konum: 'Istanbul, DES Sanayi',
    yorum_listesi: [
          {
                "kalite_puan": 3.4,
                "musteri_iliskisi_puan": 3.2,
                "surec_yonetimi_puan": 3.6,
                "yorum": "Robot teach kolunu operatTür eğitimleri çok yeterliydi. 5 operatTtür aynı gün sertifika aldı.",
                "created_at": "2026-05-02T21:52:47.660Z",
                "author": "Ugur N. - Enjeksiyon Sefi"
          },
          {
                "kalite_puan": 3.6,
                "musteri_iliskisi_puan": 3.4,
                "surec_yonetimi_puan": 3.2,
                "yorum": "Depo AGV filosuna engel tanıma kamera montajı yapıldı. Sıcak-respot sorunu neden iki hafta geçikmeye yol açtı açıklanmadı.",
                "created_at": "2025-07-27T12:27:25.981Z",
                "author": "Ceyda S. - Uretim Sorumlusu"
          }
    ],
    referans: 'Punta Kaynak Entegrasyonu, Kestirimci Bakim.',
    sektor: 'Otomotiv Ana Sanayi',
    tecrube: '10 yıl',
    uzmanlik_alani: 'Scada Sistemleri, CNC Besleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@sentetik.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556619',
    entegrator_adi: 'Vektor Kontrol Sistemleri',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'Punta Kaynak, Goruntu Isleme, PLC Programlama',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@vektor.com.tr',
    kac_kisi: 90,
    konum: 'Sakarya, 1. OSB',
    yorum_listesi: [
          {
                "kalite_puan": 4.2,
                "musteri_iliskisi_puan": 4.4,
                "surec_yonetimi_puan": 4.8,
                "yorum": "PLC kodunda deadlock durumu başlangıçta gözden kaçmıştı, 500. döngüde tetiklendi. Firmware güncellemesiyle düzeldi.",
                "created_at": "2026-02-09T17:40:05.756Z",
                "author": "Baris H. - Paketleme Lideri"
          },
          {
                "kalite_puan": 4.6,
                "musteri_iliskisi_puan": 4,
                "surec_yonetimi_puan": 4.6,
                "yorum": "Hat sonu sargı makinesi entegrasyonunda kablo yuvarlak boru çarpışma sorunu vardı. Mekanigin düşünmediği bir detay ama çabuk çözdüler.",
                "created_at": "2025-07-26T02:47:05.396Z",
                "author": "Neslihan Y. - IK ve Egitim"
          }
    ],
    referans: 'Robotik Kaynak Entegrasyonu, Hat Sonu Paletleme.',
    sektor: 'Gida',
    tecrube: '5 yıl',
    uzmanlik_alani: 'Goruntu Isleme, PLC Programlama',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@vektor.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556620',
    entegrator_adi: 'Zenith Mekatronik',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Punta Kaynak, Robotik Kaynak, AGV Sistemleri',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@zenith.com.tr',
    kac_kisi: 12,
    konum: 'Istanbul, DES Sanayi',
    yorum_listesi: [
          {
                "kalite_puan": 5,
                "musteri_iliskisi_puan": 4.8,
                "surec_yonetimi_puan": 5,
                "yorum": "Galvaniz kaplı bandırma hattında sıvı seviye sensörü yanlış konumlanmıştı. Pozisyon değiştirildi, artık sapma yok.",
                "created_at": "2025-11-23T19:50:34.869Z",
                "author": "Volkan D. - Uretim Direktoru"
          },
          {
                "kalite_puan": 4.8,
                "musteri_iliskisi_puan": 5,
                "surec_yonetimi_puan": 4.8,
                "yorum": "Robotik palet sargacı 100 devrimde gerilim aşımı alıyordu. Motor sürücsü PID ayarı düzelttikten sonra sorunsuz.",
                "created_at": "2025-07-09T08:20:35.074Z",
                "author": "Pinar E. - ISG Yoneticisi"
          }
    ],
    referans: 'Scada Sistemleri Entegrasyonu, Makine Besleme.',
    sektor: 'Plastik',
    tecrube: '17 yıl',
    uzmanlik_alani: 'Goruntu Isleme, Makine Besleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@zenith.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556621',
    entegrator_adi: 'Omega Endustriyel',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Kestirimci Bakim, Scada Sistemleri, PLC Programlama',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@omega.com.tr',
    kac_kisi: 124,
    konum: 'Bursa, NOSAB',
    yorum_listesi: [
          {
                "kalite_puan": 3,
                "musteri_iliskisi_puan": 3.4,
                "surec_yonetimi_puan": 3,
                "yorum": "Kestirimci bakım yazılımı bulut entegrasyonu çok düzülçe yapıldı; ekibimiz kendi öngörüsel modelini ekleyebiliyor.",
                "created_at": "2026-03-13T06:18:40.090Z",
                "author": "Serdar O. - Depo Yoneticisi"
          },
          {
                "kalite_puan": 3.2,
                "musteri_iliskisi_puan": 3.8,
                "surec_yonetimi_puan": 3.4,
                "yorum": "Sistem kabul testlerinde tüm KPI'lar ilk denemede geçildi. Çok az entegratör bunu başarır.",
                "created_at": "2025-10-06T17:36:53.236Z",
                "author": "Gaye R. - Tedarik Muduru"
          }
    ],
    referans: 'Punta Kaynak Entegrasyonu, CNC Besleme.',
    sektor: 'Plastik',
    tecrube: '4 yıl',
    uzmanlik_alani: 'Goruntu Isleme, Scada Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@omega.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556622',
    entegrator_adi: 'Lojik Robotik',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Scada Sistemleri, PLC Programlama, Robotik Kaynak',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@lojik.com.tr',
    kac_kisi: 72,
    konum: 'Ankara, OSTIM',
    yorum_listesi: [
          {
                "kalite_puan": 4.6,
                "musteri_iliskisi_puan": 4.2,
                "surec_yonetimi_puan": 4.4,
                "yorum": "Hattın fizibilite aşamasından devreye almaya kadar çok iyi dokümantasyon sağladılar. Eski entegratörümüze göre çok daha kurumsal.",
                "created_at": "2026-04-13T04:46:51.756Z",
                "author": "Tarik C. - Dokumhane Sefi"
          },
          {
                "kalite_puan": 4.4,
                "musteri_iliskisi_puan": 4.6,
                "surec_yonetimi_puan": 4.8,
                "yorum": "Robot yerleşim planı ilk taslakta fabrika trafik akışını bloke ediyordu. Revize teklif hızlı geldi, akış düzeltildi.",
                "created_at": "2025-07-27T08:01:26.737Z",
                "author": "Suleyman K. - Bakim Muduru"
          }
    ],
    referans: 'Goruntu Isleme Entegrasyonu, Hat Sonu Paletleme.',
    sektor: 'Ilac',
    tecrube: '14 yıl',
    uzmanlik_alani: 'Makine Besleme, Robotik Kaynak',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@lojik.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556623',
    entegrator_adi: 'Spektrum Otomasyon',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Scada Sistemleri, AGV Sistemleri, Robotik Kaynak',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@spektrum.com.tr',
    kac_kisi: 62,
    konum: 'Sakarya, 1. OSB',
    yorum_listesi: [
          {
                "kalite_puan": 4,
                "musteri_iliskisi_puan": 4.8,
                "surec_yonetimi_puan": 4,
                "yorum": "Vizyonla desteklenen çıktı sıralama sistemi aydInlatma düzenine duyarlı olduğundan gece shift’inde hata oranları yüksekti. LED armatTtür eklenerek çözüldü.",
                "created_at": "2025-12-23T12:01:43.970Z",
                "author": "Asli M. - Uretim Lideri"
          },
          {
                "kalite_puan": 4.2,
                "musteri_iliskisi_puan": 4.6,
                "surec_yonetimi_puan": 4.2,
                "yorum": "Siemens TIA Portal üzerinde yazılan blok kütpühanesi çok modTtüleer; başka hatlarımızda da kullanmayı planlIyoruz.",
                "created_at": "2025-11-10T07:25:34.294Z",
                "author": "Mesut Y. - Hat Muhendisi"
          }
    ],
    referans: 'Robotik Kaynak Entegrasyonu, Hat Sonu Paletleme.',
    sektor: 'Gida',
    tecrube: '10 yıl',
    uzmanlik_alani: 'Scada Sistemleri, CNC Besleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@spektrum.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556624',
    entegrator_adi: 'Dinamik Proses',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Robotik Kaynak, PLC Programlama, Punta Kaynak',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@dinamik.com.tr',
    kac_kisi: 109,
    konum: 'Manisa, MOSB',
    yorum_listesi: [
          {
                "kalite_puan": 4.8,
                "musteri_iliskisi_puan": 4.6,
                "surec_yonetimi_puan": 4.8,
                "yorum": "Makına talkımı çarpışma senaryolarını offline simülasıyon ile önceden yönettiler. Sahada hiç surpriz olmadı.",
                "created_at": "2026-03-02T18:58:12.099Z",
                "author": "Ibrahim T. - Proje Yoneticisi"
          },
          {
                "kalite_puan": 5,
                "musteri_iliskisi_puan": 4.8,
                "surec_yonetimi_puan": 4.6,
                "yorum": "Toz-geçirmez kabınetten çıkan ısı birikimine karşı havalandırma tasarlanırken proje ekibi ortam ısısını ölçmedi. Sonradan fan eklendi.",
                "created_at": "2025-06-30T20:24:21.363Z",
                "author": "Hasan E. - Tedarik Direktoru"
          }
    ],
    referans: 'Hat Sonu Paletleme Entegrasyonu, Makine Besleme.',
    sektor: 'Gida',
    tecrube: '24 yıl',
    uzmanlik_alani: 'Goruntu Isleme, Kestirimci Bakim',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@dinamik.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-1111-2222-3333-444455556625',
    entegrator_adi: 'Pulsar Entegrasyon',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'PLC Programlama, Robotik Kaynak, Scada Sistemleri',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@pulsar.com.tr',
    kac_kisi: 10,
    konum: 'Manisa, MOSB',
    yorum_listesi: [
          {
                "kalite_puan": 3.8,
                "musteri_iliskisi_puan": 3.6,
                "surec_yonetimi_puan": 3.4,
                "yorum": "Hassas montaj hücresi ışık korumalı kafes gerektirdi. Proje süresine eklendi ve yasal uyumluluk sağlandı.",
                "created_at": "2025-11-14T12:36:09.762Z",
                "author": "Busra V. - Uretim Sorumlusu"
          },
          {
                "kalite_puan": 4,
                "musteri_iliskisi_puan": 4,
                "surec_yonetimi_puan": 3.8,
                "yorum": "OPC-UA veri köprüsü kurulumı ilk gün çalıştı. MES entegrasyonu sıfır sorunla tamamlandı — beklentinin üzerindeydi.",
                "created_at": "2025-09-14T20:53:26.459Z",
                "author": "Kenan D. - Tesis Yoneticisi"
          }
    ],
    referans: 'Robotik Kaynak Entegrasyonu, Goruntu Isleme.',
    sektor: 'Savunma Sanayi',
    tecrube: '18 yıl',
    uzmanlik_alani: 'Scada Sistemleri, PLC Programlama',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@pulsar.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000026',
    entegrator_adi: 'Akıncı Robotik',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Robot Programlama, PLC Programlama, Mekanik Tasarım',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@akncrobotik.com.tr',
    kac_kisi: 5,
    konum: 'Bursa, NOSAB',
    yorum_listesi: [
      {
            "kalite_puan": 4.8,
            "musteri_iliskisi_puan": 4.5,
            "surec_yonetimi_puan": 4.7,
            "yorum": "Mobil HMI üzerinden alarm yönetimi ilk versiyonda iOS'ta düzgün görünmTtüyordu. Bir günce ile düzeldi, ciddi bir sorun değildi.",
            "created_at": "2025-11-10T08:20:00.000Z",
            "author": "Kadir A. - Üretim Direktörü"
      },
      {
            "kalite_puan": 4.6,
            "musteri_iliskisi_puan": 4.8,
            "surec_yonetimi_puan": 4.4,
            "yorum": "Robotun tool değişim istasyonu çok dar boşlukla yerleştirilmişti; tüç bakım teknisıyeni ulaşamIyordu. Revize edildi.",
            "created_at": "2025-08-22T14:10:00.000Z",
            "author": "Emre S. - Proje Yöneticisi"
      }
],
    referans: 'Otomotiv montaj hattı kurulumu, Pres besleme robotu entegrasyonu',
    sektor: 'Otomotiv',
    tecrube: '2 yıl',
    uzmanlik_alani: 'Makine Besleme, PLC Programlama',
    belgesi1: 'onaylandi',
    belgesi2: 'beklemede',
    belgesi3: 'null',
    created_at: new Date().toISOString(),
    email: 'info@akncrobotik.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000027',
    entegrator_adi: 'Tekform Endüstri',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Ark Kaynak Ekipmanı Devreye Alma, Robot Montaj, Elektrik İşleri',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@tekformendstri.com.tr',
    kac_kisi: 8,
    konum: 'Gebze, GOSB',
    yorum_listesi: [
      {
            "kalite_puan": 3.8,
            "musteri_iliskisi_puan": 3.5,
            "surec_yonetimi_puan": 3.2,
            "yorum": "Teslim sonrası 30 günüç keşüirim bakım ziyareti planlandı ve eksiksiz yapıldı. Çok az entegratör bu anlayışlı.",
            "created_at": "2025-09-05T09:00:00.000Z",
            "author": "Fatih Y. - Lojistik Müdürü"
      },
      {
            "kalite_puan": 4,
            "musteri_iliskisi_puan": 3.8,
            "surec_yonetimi_puan": 3.5,
            "yorum": "Programlama ekibi farklı kod tabanları başlangIçta versiyon uyuşmazlığı yaşıyordu. Git yapılandırmasından sonra takım entegrasyonu çok daha iyi.",
            "created_at": "2025-12-01T11:30:00.000Z",
            "author": "Selin T. - Tesis Yöneticisi"
      },
      {
            "kalite_puan": 4.2,
            "musteri_iliskisi_puan": 4,
            "surec_yonetimi_puan": 3.8,
            "yorum": "Paletleme robotu paket ağırlığı dengesizliklerini telafi eden dinamik tutucu vardı. Saha testleri mükkemmel geçti.",
            "created_at": "2026-01-15T16:45:00.000Z",
            "author": "Mert K. - Operasyon Şefi"
      }
],
    referans: 'Gıda paketleme hattı otomasyonu, Hat sonu paletleme sistemi',
    sektor: 'Gıda',
    tecrube: '3 yıl',
    uzmanlik_alani: 'Ark Kaynağı, Robotik Kaynak',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@tekformendstri.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000028',
    entegrator_adi: 'Atlas Otomasyon',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Robot Devreye Alma, Görüntü İşleme Entegrasyonu, Kalite Sistemi',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@atlasotomasyon.com.tr',
    kac_kisi: 12,
    konum: 'Manisa, MOSB',
    yorum_listesi: [
      {
            "kalite_puan": 5,
            "musteri_iliskisi_puan": 4.9,
            "surec_yonetimi_puan": 5,
            "yorum": "Kestirimci bakım sensTörleri makine titresim ölçümleri ile sinyal frekans analizi birleştiriyor. Çok ilerici bir yaklaşım, fabrikamızın arIza maliyeti %30 azaldı.",
            "created_at": "2025-07-18T10:00:00.000Z",
            "author": "Alp D. - Fabrika Müdürü"
      },
      {
            "kalite_puan": 4.9,
            "musteri_iliskisi_puan": 5,
            "surec_yonetimi_puan": 4.8,
            "yorum": "Elektriksel panel yazılımın öteki bölümTünden yapılan ısı iletimi kesimi hesaplanmamıştı; üretici alternatif montaj düzenlemesi önerdi.",
            "created_at": "2025-10-30T07:55:00.000Z",
            "author": "Berna Ç. - Bakım Direktörü"
      }
],
    referans: 'Savunma sanayi parça kaynak hücresi, Lazer kesim entegrasyonu',
    sektor: 'Savunma Sanayi',
    tecrube: '5 yıl',
    uzmanlik_alani: 'Görüntü İşleme, Kalite Kontrol',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@atlasotomasyon.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000029',
    entegrator_adi: 'Sentek Mühendislik',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'AGV Sistemleri Kurulum, Depo Otomasyonu, PLC Programlama',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@sentekmhendislik.com.tr',
    kac_kisi: 15,
    konum: 'Ankara, OSTİM',
    yorum_listesi: [
      {
            "kalite_puan": 4.3,
            "musteri_iliskisi_puan": 4.6,
            "surec_yonetimi_puan": 4.1,
            "yorum": "Kalıp transferi robotu tüm özelliğiyle devreye alındı, ama kullanıcı el kitabı Türkçe versiyonu gelecek ay gelecek.",
            "created_at": "2025-06-12T13:20:00.000Z",
            "author": "Hüseyin Y. - Kalite Şefi"
      },
      {
            "kalite_puan": 4.5,
            "musteri_iliskisi_puan": 4.3,
            "surec_yonetimi_puan": 4.2,
            "yorum": "Alarm yönetimi felsefesi çok iyi tasarlanmış; kritik alarmlar birincil sınıfta, bilgi alarmları üçüncü sınıfta gruplanmış.",
            "created_at": "2025-04-08T08:30:00.000Z",
            "author": "Zeynep A. - Üretim Müdürü"
      }
],
    referans: 'Tekstil fabrikası AGV filosu, Depo otomasyon yazılımı',
    sektor: 'Tekstil',
    tecrube: '5 yıl',
    uzmanlik_alani: 'Hat Sonu Paletleme, AGV Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'beklemede',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@sentekmhendislik.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000030',
    entegrator_adi: 'Protek Sistemleri',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'Scada Geliştirme, Kestirimci Bakım Sistemleri, Sensör Entegrasyonu',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@proteksistemleri.com.tr',
    kac_kisi: 20,
    konum: 'İzmir, Kemalpaşa OSB',
    yorum_listesi: [
      {
            "kalite_puan": 3.5,
            "musteri_iliskisi_puan": 3,
            "surec_yonetimi_puan": 3.2,
            "yorum": "Robotik kaynak hücresi devreye alınırken ilk hafta ark sapmıyor, kaynak dikis kalitesi spesifikasyonun üstünde (±0.3µm). Parametreleri telefonla anlatıldı, daha iyi belgeleme beklerdik.",
            "created_at": "2026-02-20T09:15:00.000Z",
            "author": "Cenk B. - Mühendis"
      },
      {
            "kalite_puan": 3.8,
            "musteri_iliskisi_puan": 3.5,
            "surec_yonetimi_puan": 3,
            "yorum": "SCADA sisteminde üretim verisi 4 saniye gecikmeli akmıştı; Siemens S7-1500 tarafında byte offset hatası tespit edildi. Üretici bunu düzeltmeden teslim etti ama remote destek 2 saatte çözdü.",
            "created_at": "2026-03-10T14:00:00.000Z",
            "author": "Oya M. - Satın Alma Müdürü"
      }
],
    referans: 'CNC tezgah besleme robotu, Görüntü işleme kalite sistemi',
    sektor: 'Talaşlı İmalat',
    tecrube: '7 yıl',
    uzmanlik_alani: 'Kestirimci Bakım, Scada Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@proteksistemleri.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000031',
    entegrator_adi: 'VeriBot Teknoloji',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Punta Kaynak Ekipmanı Montajı, Robot Eğitimi, Yedek Parça',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@veribotteknoloji.com.tr',
    kac_kisi: 25,
    konum: 'Kocaeli, Dilovası OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.7,
            "musteri_iliskisi_puan": 4.4,
            "surec_yonetimi_puan": 4.6,
            "yorum": "Hat sonu paletleme hızı saatte 1 200 kutuda kaldı, teklifteki 1 400 hedefine ulaşılamadı. Mekanik yeniden çalişılarak 6 haftada hedef yakalandı, geçikme can sıktı.",
            "created_at": "2025-05-22T11:00:00.000Z",
            "author": "Sercan D. - Kalite Direktörü"
      },
      {
            "kalite_puan": 4.5,
            "musteri_iliskisi_puan": 4.6,
            "surec_yonetimi_puan": 4.3,
            "yorum": "AGV filosu 18 aracın tümü zamanlamaya uydu, depo trafik algoritması yerinde yazıldı. Devreye alma sürecinde hiç durmaksızın üretim devam etti — çok başarılı bir planlama.",
            "created_at": "2025-08-14T15:30:00.000Z",
            "author": "Nilgün T. - Proje Koordinatörü"
      }
],
    referans: 'Scada izleme altyapısı, Kestirimci bakım sensör ağı',
    sektor: 'İlaç',
    tecrube: '8 yıl',
    uzmanlik_alani: 'PLC Programlama, Scada Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'null',
    created_at: new Date().toISOString(),
    email: 'info@veribotteknoloji.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000032',
    entegrator_adi: 'NovaTek Makine',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Hat Sonu Paletleme, Konveyör Sistemleri, Makine Besleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@novatekmakine.com.tr',
    kac_kisi: 30,
    konum: 'Gaziantep, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.1,
            "musteri_iliskisi_puan": 4.4,
            "surec_yonetimi_puan": 3.9,
            "yorum": "Görüntü işleme sistemine 0.05µm ince hata tespiti görevi verildi. Testlerde %99.2 doğru sonuç alındı, ancak kamera tutucusu tıtreme yapıyordu; çelik levha eklenerek çözüldü.",
            "created_at": "2025-12-05T10:45:00.000Z",
            "author": "Ahmet K. - Shift Amiri"
      },
      {
            "kalite_puan": 4.3,
            "musteri_iliskisi_puan": 4.2,
            "surec_yonetimi_puan": 4,
            "yorum": "PLC programı hattı yeniden yazılırken 3 farklı Omron ünitesi tek merkezi haberleşmeye bağlanmalıydı. Protokol dönüşümü başlangıçta sorun çıkardı, son haliyle çok temiz çalışıyor.",
            "created_at": "2026-01-28T08:00:00.000Z",
            "author": "Leyla S. - Bakım Şefi"
      }
],
    referans: 'İlaç ambalaj hattı robotu, Steril ortam otomasyon sistemi',
    sektor: 'Elektronik',
    tecrube: '10 yıl',
    uzmanlik_alani: 'AGV Sistemleri, Makine Besleme',
    belgesi1: 'onaylandi',
    belgesi2: 'beklemede',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@novatekmakine.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000033',
    entegrator_adi: 'Optimum Otomasyon',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Elektrik Arıza Robot Servisi, Otomasyon Arıza Servisi, Robot Bakımı',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@optimumotomasyon.com.tr',
    kac_kisi: 35,
    konum: 'Sakarya, OSGEB',
    yorum_listesi: [
      {
            "kalite_puan": 4.9,
            "musteri_iliskisi_puan": 5,
            "surec_yonetimi_puan": 4.8,
            "yorum": "Kestirimci bakım modülü 3 ayda toplam 9 planlanmamış duruluyor önledi. Titreşim sensörleri doğru yerleştirilmiş, analitik panel operatif açıdan anlaşılır.",
            "created_at": "2025-03-18T07:30:00.000Z",
            "author": "Çetin A. - Genel Müdür"
      },
      {
            "kalite_puan": 4.8,
            "musteri_iliskisi_puan": 4.7,
            "surec_yonetimi_puan": 4.9,
            "yorum": "Punta kaynak robotunda ilk 200 parcada merkezleme sapması oluştu. Firma hızlı araya girdi ve fixture toleransını sıfırlamakla çözdü; bu hızdaki yanıt takdire şayan.",
            "created_at": "2025-07-07T09:00:00.000Z",
            "author": "Pınar Y. - Operasyon Direktörü"
      }
],
    referans: 'Metal kesim ve bükme hücre entegrasyonu, Punta kaynak robotu',
    sektor: 'Metal',
    tecrube: '10 yıl',
    uzmanlik_alani: 'Robotik Kaynak, Görüntü İşleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@optimumotomasyon.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000034',
    entegrator_adi: 'TurboLine Robotics',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Mekanik Üretim, Robot Taşıma, Üretim Hattı Taşıma',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@turbolinerobotics.com.tr',
    kac_kisi: 40,
    konum: 'Konya, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 3.6,
            "musteri_iliskisi_puan": 4,
            "surec_yonetimi_puan": 3.4,
            "yorum": "Konveyör hız eşitlemesi otomotiv hattı ciklü zamanlarıyla eşleştirildi. Mekanik montaj hatasız, ama elektrik şemalama belgeleri geçici CAD olarak kaldı — as-built bekliyoruz.",
            "created_at": "2026-01-05T13:00:00.000Z",
            "author": "Gürkan D. - Kaynak Şefi"
      },
      {
            "kalite_puan": 3.9,
            "musteri_iliskisi_puan": 4.1,
            "surec_yonetimi_puan": 3.7,
            "yorum": "Makine besleme ünitesi 14” liğer döküm parçaları için optimize edildi. İlk 300 çevrimde düşenme çıkışı sıfıra indi; kapasite garantisi eksiksiz yerine getirildi.",
            "created_at": "2026-02-14T10:30:00.000Z",
            "author": "Esin Ç. - Tedarik Zinciri Müdürü"
      }
],
    referans: 'Plastik enjeksiyon tezgah besleme, Hat sonu kutulama sistemi',
    sektor: 'Plastik',
    tecrube: '12 yıl',
    uzmanlik_alani: 'Hat Sonu Paletleme, Kestirimci Bakım',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@turbolinerobotics.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000035',
    entegrator_adi: 'DigitaFab',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'PLC Programlama, Robot Programlama, Scada Sistemleri',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@digitafab.com.tr',
    kac_kisi: 45,
    konum: 'Adana, HABER OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.6,
            "musteri_iliskisi_puan": 4.3,
            "surec_yonetimi_puan": 4.5,
            "yorum": "Savunma sanayi parçası lazer kesim entegrasyonu NATO sertifikası gerektirdi. Tüm dokümantasyon tam ve zamanında teslim edildi, müfettiş denetiminde sıfır bulgu.",
            "created_at": "2025-09-25T14:00:00.000Z",
            "author": "Barış T. - Sistem Entegrasyon Müdürü"
      },
      {
            "kalite_puan": 4.4,
            "musteri_iliskisi_puan": 4.5,
            "surec_yonetimi_puan": 4.3,
            "yorum": "Gıda paketleme hattında ISO 22000 hijyen gereksinimleri nedeniyle robot bileşenleri paslanmaz çelik kaplamaya dönüştürüldü. Üretici bu konuda deneyimli ve önerisi isabetli çıktı.",
            "created_at": "2025-11-30T16:00:00.000Z",
            "author": "Sinem A. - Kalite Güvence Direktörü"
      }
],
    referans: 'Elektronik kart test otomasyonu, Vision destekli kalite kontrol',
    sektor: 'Ambalaj',
    tecrube: '14 yıl',
    uzmanlik_alani: 'Makine Besleme, Ark Kaynağı, PLC Programlama',
    belgesi1: 'onaylandi',
    belgesi2: 'beklemede',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@digitafab.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000036',
    entegrator_adi: 'PrecisBot',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Robot Programlama, PLC Programlama, Mekanik Tasarım',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@precisbot.com.tr',
    kac_kisi: 50,
    konum: 'Eskişehir, ESGEB',
    yorum_listesi: [
      {
            "kalite_puan": 4.8,
            "musteri_iliskisi_puan": 4.5,
            "surec_yonetimi_puan": 4.7,
            "yorum": "Tekstil fabrikasında boyahane lojistiği için AGV güzergaıhı yazan yazılım dinamik engel algılaması yüzünden 2 kez yeniden çaltıldı. Sonunda stabil ancak daha erken test edilebilirdi.",
            "created_at": "2025-11-10T08:20:00.000Z",
            "author": "Kadir A. - Üretim Direktörü"
      },
      {
            "kalite_puan": 4.6,
            "musteri_iliskisi_puan": 4.8,
            "surec_yonetimi_puan": 4.4,
            "yorum": "CNC tezgah besleme robotu 4 eksenli, 18 kg yük aldı. Yükleme döngüsü 8 saniye — teklifteki 9 saniyenin altında. Önerilen yakılaştirma çıkış konumu mükemmel çalıştı.",
            "created_at": "2025-08-22T14:10:00.000Z",
            "author": "Emre S. - Proje Yöneticisi"
      }
],
    referans: 'Otomotiv montaj hattı kurulumu, Pres besleme robotu entegrasyonu',
    sektor: 'Otomotiv',
    tecrube: '15 yıl',
    uzmanlik_alani: 'Görüntü İşleme, PLC Programlama, Scada Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'null',
    created_at: new Date().toISOString(),
    email: 'info@precisbot.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000037',
    entegrator_adi: 'Anadolu Otomasyon',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Ark Kaynak Ekipmanı Devreye Alma, Robot Montaj, Elektrik İşleri',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@anadoluotomasyon.com.tr',
    kac_kisi: 60,
    konum: 'Tekirdağ, ÇERKEZKÖY OSB',
    yorum_listesi: [
      {
            "kalite_puan": 3.8,
            "musteri_iliskisi_puan": 3.5,
            "surec_yonetimi_puan": 3.2,
            "yorum": "İlaç ambalaj hattında süreklilik önemliydi; firma gece shift’iyle devreye aldı. Hipersteril oda sertifikası aldıkça prosedEr adlandı düşürmüştü ama düzeltti.",
            "created_at": "2025-09-05T09:00:00.000Z",
            "author": "Fatih Y. - Lojistik Müdürü"
      },
      {
            "kalite_puan": 4,
            "musteri_iliskisi_puan": 3.8,
            "surec_yonetimi_puan": 3.5,
            "yorum": "Elektronik kart test otomasyon sistemi ıskalası fabrikasına kuruldu. Vision tarafı çalışıyor ancak raporlama modülü kaçınması gereken false-positive üretiyor, güncelleme bekliyor.",
            "created_at": "2025-12-01T11:30:00.000Z",
            "author": "Selin T. - Tesis Yöneticisi"
      },
      {
            "kalite_puan": 4.2,
            "musteri_iliskisi_puan": 4,
            "surec_yonetimi_puan": 3.8,
            "yorum": "Plastik enjeksiyon tezgahının robot araçlığı sprue kesici entegrasyonu beklenmedik vakum başarısızlığına uğradi. Tasarimi revize ettiler, kalite daha iyi.",
            "created_at": "2026-01-15T16:45:00.000Z",
            "author": "Mert K. - Operasyon Şefi"
      }
],
    referans: 'Gıda paketleme hattı otomasyonu, Hat sonu paletleme sistemi',
    sektor: 'Gıda',
    tecrube: '16 yıl',
    uzmanlik_alani: 'AGV Sistemleri, Robotik Kaynak, Hat Sonu Paletleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@anadoluotomasyon.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000038',
    entegrator_adi: 'Mekatek Sistemleri',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Robot Devreye Alma, Görüntü İşleme Entegrasyonu, Kalite Sistemi',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@mekateksistemleri.com.tr',
    kac_kisi: 70,
    konum: 'Denizli, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 5,
            "musteri_iliskisi_puan": 4.9,
            "surec_yonetimi_puan": 5,
            "yorum": "Metal bükme ve presleme hücresinde servo kaynaklı parça poz pozlaması çok hassas. 6 saat mühendisin saha desteği ile yapılandırma tamamlandı.",
            "created_at": "2025-07-18T10:00:00.000Z",
            "author": "Alp D. - Fabrika Müdürü"
      },
      {
            "kalite_puan": 4.9,
            "musteri_iliskisi_puan": 5,
            "surec_yonetimi_puan": 4.8,
            "yorum": "Depo otomasyon sisteminde RF barkod okuyucu şeridsği firmware hatası kaynaklı çökme yaşıyordu. Firmware güncellemesi sonrası kesintisiz çalıştı.",
            "created_at": "2025-10-30T07:55:00.000Z",
            "author": "Berna Ç. - Bakım Direktörü"
      }
],
    referans: 'Savunma sanayi parça kaynak hücresi, Lazer kesim entegrasyonu',
    sektor: 'Savunma Sanayi',
    tecrube: '18 yıl',
    uzmanlik_alani: 'Kestirimci Bakım, Makine Besleme',
    belgesi1: 'onaylandi',
    belgesi2: 'beklemede',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@mekateksistemleri.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000039',
    entegrator_adi: 'İnofab Robotik',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'AGV Sistemleri Kurulum, Depo Otomasyonu, PLC Programlama',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@inofabrobotik.com.tr',
    kac_kisi: 80,
    konum: 'İstanbul, İkitelli OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.3,
            "musteri_iliskisi_puan": 4.6,
            "surec_yonetimi_puan": 4.1,
            "yorum": "Ambalaj hattı robot pnomatik sistemi yeni çift-katlı valf grubuyla yenilendi. Gücü düşükken yavaslayan kol sorunu çözüldü; verimlilik %18 arttı.",
            "created_at": "2025-06-12T13:20:00.000Z",
            "author": "Hüseyin Y. - Kalite Şefi"
      },
      {
            "kalite_puan": 4.5,
            "musteri_iliskisi_puan": 4.3,
            "surec_yonetimi_puan": 4.2,
            "yorum": "Otomotiv karoser kaynak hattı entegrasyonunda jig toleransı ±0.1 mm'ye düşürüldü. 3 yeni robot kola ek olarak mevcut 5 kol da yeniden kalibre edildi, hepsi tek oturumda.",
            "created_at": "2025-04-08T08:30:00.000Z",
            "author": "Zeynep A. - Üretim Müdürü"
      }
],
    referans: 'Tekstil fabrikası AGV filosu, Depo otomasyon yazılımı',
    sektor: 'Tekstil',
    tecrube: '18 yıl',
    uzmanlik_alani: 'Scada Sistemleri, PLC Programlama, AGV Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@inofabrobotik.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000040',
    entegrator_adi: 'SigoTek',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'Scada Geliştirme, Kestirimci Bakım Sistemleri, Sensör Entegrasyonu',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@sigotek.com.tr',
    kac_kisi: 90,
    konum: 'Kayseri, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 3.5,
            "musteri_iliskisi_puan": 3,
            "surec_yonetimi_puan": 3.2,
            "yorum": "Härterei fırın sıcaklık SCADA izleme sistemi kuruldu. Alarm eşiği yanlış ayarlanmıştı, ilk haftada gerçek alarm olmayan tetikleme oluştu ama hızlı düzeldi.",
            "created_at": "2026-02-20T09:15:00.000Z",
            "author": "Cenk B. - Mühendis"
      },
      {
            "kalite_puan": 3.8,
            "musteri_iliskisi_puan": 3.5,
            "surec_yonetimi_puan": 3,
            "yorum": "Gıda düzültme ve küpürdatma hattında vision sistemi renk bazlı kusur tespiti yapıyor. Performans beklenenden iyi; erken teslim bile gerçekleşti.",
            "created_at": "2026-03-10T14:00:00.000Z",
            "author": "Oya M. - Satın Alma Müdürü"
      }
],
    referans: 'CNC tezgah besleme robotu, Görüntü işleme kalite sistemi',
    sektor: 'Talaşlı İmalat',
    tecrube: '20 yıl',
    uzmanlik_alani: 'Ark Kaynağı, Kestirimci Bakım, Görüntü İşleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@sigotek.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000041',
    entegrator_adi: 'Delta Endüstriyel',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Punta Kaynak Ekipmanı Montajı, Robot Eğitimi, Yedek Parça',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@deltaendstriyel.com.tr',
    kac_kisi: 100,
    konum: 'Samsun, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.7,
            "musteri_iliskisi_puan": 4.4,
            "surec_yonetimi_puan": 4.6,
            "yorum": "Proje boyunca gerçek zamanlı haftalık ilerleme raporu alındı. Bazı raporlar veri eksikti ama hafta içinde tamamlandı.",
            "created_at": "2025-05-22T11:00:00.000Z",
            "author": "Sercan D. - Kalite Direktörü"
      },
      {
            "kalite_puan": 4.5,
            "musteri_iliskisi_puan": 4.6,
            "surec_yonetimi_puan": 4.3,
            "yorum": "Robot yeniden programlama sürecinde üretim 6 saat durdu, planıanan 4 saat yerine. Ek mesai bedeli tazmin edilmedi; sözleşme nettir.",
            "created_at": "2025-08-14T15:30:00.000Z",
            "author": "Nilgün T. - Proje Koordinatörü"
      }
],
    referans: 'Scada izleme altyapısı, Kestirimci bakım sensör ağı',
    sektor: 'İlaç',
    tecrube: '20 yıl',
    uzmanlik_alani: 'Hat Sonu Paletleme, Makine Besleme',
    belgesi1: 'onaylandi',
    belgesi2: 'beklemede',
    belgesi3: 'null',
    created_at: new Date().toISOString(),
    email: 'info@deltaendstriyel.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000042',
    entegrator_adi: 'Volt Entegrasyon',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Hat Sonu Paletleme, Konveyör Sistemleri, Makine Besleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@voltentegrasyon.com.tr',
    kac_kisi: 110,
    konum: 'Malatya, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.1,
            "musteri_iliskisi_puan": 4.4,
            "surec_yonetimi_puan": 3.9,
            "yorum": "Devreye alma sonrası ilk ayda 3 kez teknik ekip sahıya geldi. Her defasında sorunu uzaktan da çözebilirlerdi ama yerinde çözmeyi tercih ettiler.",
            "created_at": "2025-12-05T10:45:00.000Z",
            "author": "Ahmet K. - Shift Amiri"
      },
      {
            "kalite_puan": 4.3,
            "musteri_iliskisi_puan": 4.2,
            "surec_yonetimi_puan": 4,
            "yorum": "Hat durma süresi ilk çeyrekte %2.1'den %0.4'e indi. En büyük katkı konveyör senkronizasyon iyileştirmesinden geldi.",
            "created_at": "2026-01-28T08:00:00.000Z",
            "author": "Leyla S. - Bakım Şefi"
      }
],
    referans: 'İlaç ambalaj hattı robotu, Steril ortam otomasyon sistemi',
    sektor: 'Elektronik',
    tecrube: '22 yıl',
    uzmanlik_alani: 'Robotik Kaynak, PLC Programlama',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@voltentegrasyon.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000043',
    entegrator_adi: 'KineTek Makine',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Elektrik Arıza Robot Servisi, Otomasyon Arıza Servisi, Robot Bakımı',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@kinetekmakine.com.tr',
    kac_kisi: 120,
    konum: 'Trabzon, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.9,
            "musteri_iliskisi_puan": 5,
            "surec_yonetimi_puan": 4.8,
            "yorum": "Üretim sırasında hattan geçen ilk 1000 parça sıfır hurda ile tamamlandı. Bazı hizalama ayarı gerekti ama sonunda mükemmel.",
            "created_at": "2025-03-18T07:30:00.000Z",
            "author": "Çetin A. - Genel Müdür"
      },
      {
            "kalite_puan": 4.8,
            "musteri_iliskisi_puan": 4.7,
            "surec_yonetimi_puan": 4.9,
            "yorum": "Sistem devreye alırken eski PLC ile yeni SCADA arasındaki Modbus haberleşmesi çaklıyordu. Çözüm bir hafta sürdü ama çok kalıcı.",
            "created_at": "2025-07-07T09:00:00.000Z",
            "author": "Pınar Y. - Operasyon Direktörü"
      }
],
    referans: 'Metal kesim ve bükme hücre entegrasyonu, Punta kaynak robotu',
    sektor: 'Metal',
    tecrube: '25 yıl',
    uzmanlik_alani: 'Görüntü İşleme, AGV Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@kinetekmakine.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000044',
    entegrator_adi: 'Apex Robotik',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Mekanik Üretim, Robot Taşıma, Üretim Hattı Taşıma',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@apexrobotik.com.tr',
    kac_kisi: 130,
    konum: 'Antalya, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 3.6,
            "musteri_iliskisi_puan": 4,
            "surec_yonetimi_puan": 3.4,
            "yorum": "Robot yolunu yeniden öğrenmeden önce simlasön çallıştırıldı, sahıda hiç çarpışma olmadı.",
            "created_at": "2026-01-05T13:00:00.000Z",
            "author": "Gürkan D. - Kaynak Şefi"
      },
      {
            "kalite_puan": 3.9,
            "musteri_iliskisi_puan": 4.1,
            "surec_yonetimi_puan": 3.7,
            "yorum": "Konveyör bantları gıda standartlarına uygun malzemeyle değiştirildi. Bant ek kalitesi beklentinin üstünde.",
            "created_at": "2026-02-14T10:30:00.000Z",
            "author": "Esin Ç. - Tedarik Zinciri Müdürü"
      }
],
    referans: 'Plastik enjeksiyon tezgah besleme, Hat sonu kutulama sistemi',
    sektor: 'Plastik',
    tecrube: '3 yıl',
    uzmanlik_alani: 'Scada Sistemleri, Kestirimci Bakım',
    belgesi1: 'onaylandi',
    belgesi2: 'beklemede',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@apexrobotik.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000045',
    entegrator_adi: 'StellarFab',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'PLC Programlama, Robot Programlama, Scada Sistemleri',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@stellarfab.com.tr',
    kac_kisi: 140,
    konum: 'Mersin, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.6,
            "musteri_iliskisi_puan": 4.3,
            "surec_yonetimi_puan": 4.5,
            "yorum": "Güvenlik çiti lazer perdesiyle entegre edildi. İlk testlerde tetikleme gecikmesi standartın altındaydı; yeniden ayarlandı.",
            "created_at": "2025-09-25T14:00:00.000Z",
            "author": "Barış T. - Sistem Entegrasyon Müdürü"
      },
      {
            "kalite_puan": 4.4,
            "musteri_iliskisi_puan": 4.5,
            "surec_yonetimi_puan": 4.3,
            "yorum": "Servo motor parametreleri fabıça sahaya gelip yerinde optimize etti. Ekstra gidip gelme hem zaman hem bizçin çaba harcattı ama sonunda sert çalıştı.",
            "created_at": "2025-11-30T16:00:00.000Z",
            "author": "Sinem A. - Kalite Güvence Direktörü"
      }
],
    referans: 'Elektronik kart test otomasyonu, Vision destekli kalite kontrol',
    sektor: 'Ambalaj',
    tecrube: '6 yıl',
    uzmanlik_alani: 'PLC Programlama, Ark Kaynağı, Hat Sonu Paletleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@stellarfab.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000046',
    entegrator_adi: 'CoreLine Otomasyon',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Robot Programlama, PLC Programlama, Mekanik Tasarım',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@corelineotomasyon.com.tr',
    kac_kisi: 15,
    konum: 'Balıkesir, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.8,
            "musteri_iliskisi_puan": 4.5,
            "surec_yonetimi_puan": 4.7,
            "yorum": "Fabrikasımızdaki pres beslemede vakum kavrama basıncı tutarsız çıkıyordu; valf temizlenerek çözüldü, takip çok hızlıydı.",
            "created_at": "2025-11-10T08:20:00.000Z",
            "author": "Kadir A. - Üretim Direktörü"
      },
      {
            "kalite_puan": 4.6,
            "musteri_iliskisi_puan": 4.8,
            "surec_yonetimi_puan": 4.4,
            "yorum": "Robot teach kolunu operatTür eğitimleri çok yeterliydi. 5 operatTtür aynı gün sertifika aldı.",
            "created_at": "2025-08-22T14:10:00.000Z",
            "author": "Emre S. - Proje Yöneticisi"
      }
],
    referans: 'Otomotiv montaj hattı kurulumu, Pres besleme robotu entegrasyonu',
    sektor: 'Otomotiv',
    tecrube: '9 yıl',
    uzmanlik_alani: 'Makine Besleme, Görüntü İşleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'null',
    created_at: new Date().toISOString(),
    email: 'info@corelineotomasyon.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000047',
    entegrator_adi: 'Quantum Makine',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Ark Kaynak Ekipmanı Devreye Alma, Robot Montaj, Elektrik İşleri',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@quantummakine.com.tr',
    kac_kisi: 28,
    konum: 'Çorum, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 3.8,
            "musteri_iliskisi_puan": 3.5,
            "surec_yonetimi_puan": 3.2,
            "yorum": "Depo AGV filosuna engel tanıma kamera montajı yapıldı. Sıcak-respot sorunu neden iki hafta geçikmeye yol açtı açıklanmadı.",
            "created_at": "2025-09-05T09:00:00.000Z",
            "author": "Fatih Y. - Lojistik Müdürü"
      },
      {
            "kalite_puan": 4,
            "musteri_iliskisi_puan": 3.8,
            "surec_yonetimi_puan": 3.5,
            "yorum": "PLC kodunda deadlock durumu başlangıçta gözden kaçmıştı, 500. döngüde tetiklendi. Firmware güncellemesiyle düzeldi.",
            "created_at": "2025-12-01T11:30:00.000Z",
            "author": "Selin T. - Tesis Yöneticisi"
      },
      {
            "kalite_puan": 4.2,
            "musteri_iliskisi_puan": 4,
            "surec_yonetimi_puan": 3.8,
            "yorum": "Hat sonu sargı makinesi entegrasyonunda kablo yuvarlak boru çarpışma sorunu vardı. Mekanigin düşünmediği bir detay ama çabuk çözdüler.",
            "created_at": "2026-01-15T16:45:00.000Z",
            "author": "Mert K. - Operasyon Şefi"
      }
],
    referans: 'Gıda paketleme hattı otomasyonu, Hat sonu paletleme sistemi',
    sektor: 'Gıda',
    tecrube: '11 yıl',
    uzmanlik_alani: 'AGV Sistemleri, Scada Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'beklemede',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@quantummakine.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000048',
    entegrator_adi: 'FlexBot Sistemleri',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Robot Devreye Alma, Görüntü İşleme Entegrasyonu, Kalite Sistemi',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@flexbotsistemleri.com.tr',
    kac_kisi: 42,
    konum: 'Elazığ, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 5,
            "musteri_iliskisi_puan": 4.9,
            "surec_yonetimi_puan": 5,
            "yorum": "Galvaniz kaplı bandırma hattında sıvı seviye sensörü yanlış konumlanmıştı. Pozisyon değiştirildi, artık sapma yok.",
            "created_at": "2025-07-18T10:00:00.000Z",
            "author": "Alp D. - Fabrika Müdürü"
      },
      {
            "kalite_puan": 4.9,
            "musteri_iliskisi_puan": 5,
            "surec_yonetimi_puan": 4.8,
            "yorum": "Robotik palet sargacı 100 devrimde gerilim aşımı alıyordu. Motor sürücsü PID ayarı düzelttikten sonra sorunsuz.",
            "created_at": "2025-10-30T07:55:00.000Z",
            "author": "Berna Ç. - Bakım Direktörü"
      }
],
    referans: 'Savunma sanayi parça kaynak hücresi, Lazer kesim entegrasyonu',
    sektor: 'Savunma Sanayi',
    tecrube: '13 yıl',
    uzmanlik_alani: 'Kestirimci Bakım, Robotik Kaynak',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@flexbotsistemleri.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000049',
    entegrator_adi: 'OmegaTek Endüstri',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'AGV Sistemleri Kurulum, Depo Otomasyonu, PLC Programlama',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@omegatekendstri.com.tr',
    kac_kisi: 55,
    konum: 'Erzurum, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.3,
            "musteri_iliskisi_puan": 4.6,
            "surec_yonetimi_puan": 4.1,
            "yorum": "Kestirimci bakım yazılımı bulut entegrasyonu çok düzülçe yapıldı; ekibimiz kendi öngörüsel modelini ekleyebiliyor.",
            "created_at": "2025-06-12T13:20:00.000Z",
            "author": "Hüseyin Y. - Kalite Şefi"
      },
      {
            "kalite_puan": 4.5,
            "musteri_iliskisi_puan": 4.3,
            "surec_yonetimi_puan": 4.2,
            "yorum": "Sistem kabul testlerinde tüm KPI'lar ilk denemede geçildi. Çok az entegratör bunu başarır.",
            "created_at": "2025-04-08T08:30:00.000Z",
            "author": "Zeynep A. - Üretim Müdürü"
      }
],
    referans: 'Tekstil fabrikası AGV filosu, Depo otomasyon yazılımı',
    sektor: 'Tekstil',
    tecrube: '17 yıl',
    uzmanlik_alani: 'Hat Sonu Paletleme, PLC Programlama',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@omegatekendstri.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000050',
    entegrator_adi: 'NanoLine',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'Scada Geliştirme, Kestirimci Bakım Sistemleri, Sensör Entegrasyonu',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@nanoline.com.tr',
    kac_kisi: 65,
    konum: 'Van, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 3.5,
            "musteri_iliskisi_puan": 3,
            "surec_yonetimi_puan": 3.2,
            "yorum": "Hattın fizibilite aşamasından devreye almaya kadar çok iyi dokümantasyon sağladılar. Eski entegratörümüze göre çok daha kurumsal.",
            "created_at": "2026-02-20T09:15:00.000Z",
            "author": "Cenk B. - Mühendis"
      },
      {
            "kalite_puan": 3.8,
            "musteri_iliskisi_puan": 3.5,
            "surec_yonetimi_puan": 3,
            "yorum": "Robot yerleşim planı ilk taslakta fabrika trafik akışını bloke ediyordu. Revize teklif hızlı geldi, akış düzeltildi.",
            "created_at": "2026-03-10T14:00:00.000Z",
            "author": "Oya M. - Satın Alma Müdürü"
      }
],
    referans: 'CNC tezgah besleme robotu, Görüntü işleme kalite sistemi',
    sektor: 'Talaşlı İmalat',
    tecrube: '4 yıl',
    uzmanlik_alani: 'Görüntü İşleme, Makine Besleme, Ark Kaynağı',
    belgesi1: 'onaylandi',
    belgesi2: 'beklemede',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@nanoline.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000051',
    entegrator_adi: 'IndusPro Robotik',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Punta Kaynak Ekipmanı Montajı, Robot Eğitimi, Yedek Parça',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@indusprorobotik.com.tr',
    kac_kisi: 35,
    konum: 'Hatay, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.7,
            "musteri_iliskisi_puan": 4.4,
            "surec_yonetimi_puan": 4.6,
            "yorum": "Vizyonla desteklenen çıktı sıralama sistemi aydInlatma düzenine duyarlı olduğundan gece shift’inde hata oranları yüksekti. LED armatTtür eklenerek çözüldü.",
            "created_at": "2025-05-22T11:00:00.000Z",
            "author": "Sercan D. - Kalite Direktörü"
      },
      {
            "kalite_puan": 4.5,
            "musteri_iliskisi_puan": 4.6,
            "surec_yonetimi_puan": 4.3,
            "yorum": "Siemens TIA Portal üzerinde yazılan blok kütpühanesi çok modTtüleer; başka hatlarımızda da kullanmayı planlIyoruz.",
            "created_at": "2025-08-14T15:30:00.000Z",
            "author": "Nilgün T. - Proje Koordinatörü"
      }
],
    referans: 'Scada izleme altyapısı, Kestirimci bakım sensör ağı',
    sektor: 'İlaç',
    tecrube: '7 yıl',
    uzmanlik_alani: 'Robotik Kaynak, AGV Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'null',
    created_at: new Date().toISOString(),
    email: 'info@indusprorobotik.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000052',
    entegrator_adi: 'BioTek Otomasyon',
    entegrator_buyuklugu: 'kucuk',
    faaliyet_alanlari: 'Hat Sonu Paletleme, Konveyör Sistemleri, Makine Besleme',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@biotekotomasyon.com.tr',
    kac_kisi: 85,
    konum: 'Muğla, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.1,
            "musteri_iliskisi_puan": 4.4,
            "surec_yonetimi_puan": 3.9,
            "yorum": "Makına talkımı çarpışma senaryolarını offline simülasıyon ile önceden yönettiler. Sahada hiç surpriz olmadı.",
            "created_at": "2025-12-05T10:45:00.000Z",
            "author": "Ahmet K. - Shift Amiri"
      },
      {
            "kalite_puan": 4.3,
            "musteri_iliskisi_puan": 4.2,
            "surec_yonetimi_puan": 4,
            "yorum": "Toz-geçirmez kabınetten çıkan ısı birikimine karşı havalandırma tasarlanırken proje ekibi ortam ısısını ölçmedi. Sonradan fan eklendi.",
            "created_at": "2026-01-28T08:00:00.000Z",
            "author": "Leyla S. - Bakım Şefi"
      }
],
    referans: 'İlaç ambalaj hattı robotu, Steril ortam otomasyon sistemi',
    sektor: 'Elektronik',
    tecrube: '19 yıl',
    uzmanlik_alani: 'Scada Sistemleri, Hat Sonu Paletleme',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@biotekotomasyon.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000053',
    entegrator_adi: 'FirmaTek Makine',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Elektrik Arıza Robot Servisi, Otomasyon Arıza Servisi, Robot Bakımı',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@firmatekmakine.com.tr',
    kac_kisi: 22,
    konum: 'Nevşehir, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.9,
            "musteri_iliskisi_puan": 5,
            "surec_yonetimi_puan": 4.8,
            "yorum": "Hassas montaj hücresi ışık korumalı kafes gerektirdi. Proje süresine eklendi ve yasal uyumluluk sağlandı.",
            "created_at": "2025-03-18T07:30:00.000Z",
            "author": "Çetin A. - Genel Müdür"
      },
      {
            "kalite_puan": 4.8,
            "musteri_iliskisi_puan": 4.7,
            "surec_yonetimi_puan": 4.9,
            "yorum": "OPC-UA veri köprüsü kurulumı ilk gün çalıştı. MES entegrasyonu sıfır sorunla tamamlandı — beklentinin üzerindeydi.",
            "created_at": "2025-07-07T09:00:00.000Z",
            "author": "Pınar Y. - Operasyon Direktörü"
      }
],
    referans: 'Metal kesim ve bükme hücre entegrasyonu, Punta kaynak robotu',
    sektor: 'Metal',
    tecrube: '8 yıl',
    uzmanlik_alani: 'PLC Programlama, Kestirimci Bakım',
    belgesi1: 'onaylandi',
    belgesi2: 'beklemede',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@firmatekmakine.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000054',
    entegrator_adi: 'AlphaTek Endüstri',
    entegrator_buyuklugu: 'orta',
    faaliyet_alanlari: 'Mekanik Üretim, Robot Taşıma, Üretim Hattı Taşıma',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@alphatekendstri.com.tr',
    kac_kisi: 48,
    konum: 'Afyon, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 3.6,
            "musteri_iliskisi_puan": 4,
            "surec_yonetimi_puan": 3.4,
            "yorum": "Mobil HMI üzerinden alarm yönetimi ilk versiyonda iOS'ta düzgün görünmTtüyordu. Bir günce ile düzeldi, ciddi bir sorun değildi.",
            "created_at": "2026-01-05T13:00:00.000Z",
            "author": "Gürkan D. - Kaynak Şefi"
      },
      {
            "kalite_puan": 3.9,
            "musteri_iliskisi_puan": 4.1,
            "surec_yonetimi_puan": 3.7,
            "yorum": "Robotun tool değişim istasyonu çok dar boşlukla yerleştirilmişti; tüç bakım teknisıyeni ulaşamIyordu. Revize edildi.",
            "created_at": "2026-02-14T10:30:00.000Z",
            "author": "Esin Ç. - Tedarik Zinciri Müdürü"
      }
],
    referans: 'Plastik enjeksiyon tezgah besleme, Hat sonu kutulama sistemi',
    sektor: 'Plastik',
    tecrube: '15 yıl',
    uzmanlik_alani: 'Ark Kaynağı, Görüntü İşleme, PLC Programlama',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@alphatekendstri.com.tr',
    user_id: null,
    yorumlar: null,
  },
  {
    id: 'e1a1b1c1-2222-3333-4444-555500000055',
    entegrator_adi: 'ZenBot Sistemleri',
    entegrator_buyuklugu: 'buyuk',
    faaliyet_alanlari: 'PLC Programlama, Robot Programlama, Scada Sistemleri',
    hizmet_verilen_iller: 'Tüm Türkiye',
    iletisim_sosyal_medya: 'info@zenbotsistemleri.com.tr',
    kac_kisi: 75,
    konum: 'Isparta, OSB',
    yorum_listesi: [
      {
            "kalite_puan": 4.6,
            "musteri_iliskisi_puan": 4.3,
            "surec_yonetimi_puan": 4.5,
            "yorum": "Teslim sonrası 30 günüç keşüirim bakım ziyareti planlandı ve eksiksiz yapıldı. Çok az entegratör bu anlayışlı.",
            "created_at": "2025-09-25T14:00:00.000Z",
            "author": "Barış T. - Sistem Entegrasyon Müdürü"
      },
      {
            "kalite_puan": 4.4,
            "musteri_iliskisi_puan": 4.5,
            "surec_yonetimi_puan": 4.3,
            "yorum": "Programlama ekibi farklı kod tabanları başlangIçta versiyon uyuşmazlığı yaşıyordu. Git yapılandırmasından sonra takım entegrasyonu çok daha iyi.",
            "created_at": "2025-11-30T16:00:00.000Z",
            "author": "Sinem A. - Kalite Güvence Direktörü"
      }
],
    referans: 'Elektronik kart test otomasyonu, Vision destekli kalite kontrol',
    sektor: 'Ambalaj',
    tecrube: '12 yıl',
    uzmanlik_alani: 'Makine Besleme, Scada Sistemleri',
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'info@zenbotsistemleri.com.tr',
    user_id: null,
    yorumlar: null,
  }
];


const calculateAverages = (yorumlar: any[]) => {
  if (!yorumlar || yorumlar.length === 0) {
    return { kalite: 0, musteri_iliskisi: 0, surec: 0, genel: 0 };
  }
  
  let totalK = 0, totalM = 0, totalS = 0;
  yorumlar.forEach(y => {
    totalK += y.kalite_puan;
    totalM += y.musteri_iliskisi_puan;
    totalS += y.surec_yonetimi_puan;
  });
  
  const count = yorumlar.length;
  const kalite = Number((totalK / count).toFixed(1));
  const musteri_iliskisi = Number((totalM / count).toFixed(1));
  const surec = Number((totalS / count).toFixed(1));
  const genel = Number(((kalite + musteri_iliskisi + surec) / 3).toFixed(1));
  
  return { kalite, musteri_iliskisi, surec, genel };
};

export const mockEntegratorler: MockEntegrator[] = rawEntegratorler.map(ent => {
  const avgs = calculateAverages(ent.yorum_listesi || []);
  return {
    ...ent,
    puan: avgs.genel,
    detayli_puanlar: {
      kalite: avgs.kalite,
      musteri_iliskisi: avgs.musteri_iliskisi,
      surec: avgs.surec
    }
  } as MockEntegrator;
});

export const mockFirmalar: Firma[] = [
  {
    id: 'f2b2c2d2-1111-2222-3333-444455556601',
    firma_adi: 'Anatolia Otomotiv A.Ş.',
    firma_olcegi: 'buyuk',
    firma_tanitim_yazisi: 'Otomotiv ana sanayi için yüksek hassasiyetli şasi ve gövde parçaları üreten köklü bir kuruluş.',
    kredi: 150,
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    belgesi4: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'satinalma@anatoliaotomotiv.com',
    user_id: null,
  },
  {
    id: 'f2b2c2d2-1111-2222-3333-444455556602',
    firma_adi: 'Başaran Gıda Sanayi',
    firma_olcegi: 'orta',
    firma_tanitim_yazisi: 'Atıştırmalık ürünler ve unlu mamuller üreten, günde 100 ton kapasiteli üretim tesisi.',
    kredi: 80,
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: null,
    belgesi4: null,
    created_at: new Date().toISOString(),
    email: 'info@basarangida.com',
    user_id: null,
  },
  {
    id: 'f2b2c2d2-1111-2222-3333-444455556603',
    firma_adi: 'Demirkan Metal İşleme',
    firma_olcegi: 'kucuk',
    firma_tanitim_yazisi: 'CNC torna ve freze işlemleriyle savunma sanayi ve otomotiv sektörüne talaşlı imalat hizmeti veriyoruz.',
    kredi: 30,
    belgesi1: 'onaylandi',
    belgesi2: null,
    belgesi3: null,
    belgesi4: null,
    created_at: new Date().toISOString(),
    email: 'iletisim@demirkanmetal.com',
    user_id: null,
  },
  {
    id: 'f2b2c2d2-1111-2222-3333-444455556604',
    firma_adi: 'YurtPlastik Ambalaj',
    firma_olcegi: 'orta',
    firma_tanitim_yazisi: 'Endüstriyel plastik palet ve taşıma kutuları üretiminde öncü.',
    kredi: 50,
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    belgesi4: null,
    created_at: new Date().toISOString(),
    email: 'info@yurtplastik.com.tr',
    user_id: null,
  },
  {
    id: 'f2b2c2d2-1111-2222-3333-444455556605',
    firma_adi: 'Ege Elektronik Üretim',
    firma_olcegi: 'buyuk',
    firma_tanitim_yazisi: 'Tüketici elektroniği, PCB dizgi ve test süreçlerinde yüksek teknoloji altyapısına sahip üretim merkezi.',
    kredi: 120,
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    belgesi4: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'satinalma@egeelektronik.com',
    user_id: null,
  },
  {
    id: 'f2b2c2d2-1111-2222-3333-444455556606',
    firma_adi: 'Güven İlaç Sanayi',
    firma_olcegi: 'global',
    firma_tanitim_yazisi: 'Uluslararası standartlarda steril ilaç üretimi yapan global vizyona sahip sağlık firması.',
    kredi: 500,
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    belgesi4: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'tender@guvenilac.com.tr',
    user_id: null,
  },
  {
    id: 'f2b2c2d2-1111-2222-3333-444455556607',
    firma_adi: 'Zirve Beyaz Eşya',
    firma_olcegi: 'buyuk',
    firma_tanitim_yazisi: 'Ankastre fırın, ocak ve davlumbaz üretiminde Türkiye pazarının parlayan yıldızı.',
    kredi: 90,
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    belgesi4: null,
    created_at: new Date().toISOString(),
    email: 'info@zirvebeyazesya.com',
    user_id: null,
  },
  {
    id: 'f2b2c2d2-1111-2222-3333-444455556608',
    firma_adi: 'Marmara Havacılık',
    firma_olcegi: 'buyuk',
    firma_tanitim_yazisi: 'Havacılık yapısal parçaları için kompozit ve alüminyum alaşımlı komponent üretimi.',
    kredi: 200,
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    belgesi4: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'supplychain@marmarahavacilik.com',
    user_id: null,
  },
  {
    id: 'f2b2c2d2-1111-2222-3333-444455556609',
    firma_adi: 'ÇelikKutu Ambalaj',
    firma_olcegi: 'kucuk',
    firma_tanitim_yazisi: 'Metal teneke kutu üretiminde butik ve hızlı çözümler sunan üretim atölyesi.',
    kredi: 15,
    belgesi1: 'onaylandi',
    belgesi2: null,
    belgesi3: null,
    belgesi4: null,
    created_at: new Date().toISOString(),
    email: 'info@celikkutu.com',
    user_id: null,
  },
  {
    id: 'f2b2c2d2-1111-2222-3333-444455556610',
    firma_adi: 'Asya Savunma Sistemleri',
    firma_olcegi: 'orta',
    firma_tanitim_yazisi: 'Zırhlı araç sistemleri için alt parçalar üreten, milli teknoloji hamlesi destekçisi.',
    kredi: 60,
    belgesi1: 'onaylandi',
    belgesi2: 'onaylandi',
    belgesi3: 'onaylandi',
    belgesi4: 'onaylandi',
    created_at: new Date().toISOString(),
    email: 'ihale@asyasavunma.com',
    user_id: null,
  }
];
